import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Learn section sidebar
  learnSidebar: [
    {
      type: 'doc',
      id: 'learn/index',
      label: 'Learn',
    },
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'learn/introduction/what-is-yellow-sdk',
        'learn/introduction/yellow-apps',
      ],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Beginner',
      items: [
        'learn/beginner/app-session-management',
      ],
      collapsible: false,
      collapsed: false,
    },
  ],
  
  // Build section sidebar
  buildSidebar: [
    {
      type: 'autogenerated',
      dirName: 'build',
    },
  ],
  
  // Manuals section sidebar
  manualsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'manuals',
    },
  ],
  
  // Tutorials section sidebar
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  
  // API Reference section sidebar
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
  
  // Legacy section sidebar
  legacySidebar: [
    {
      type: 'autogenerated',
      dirName: 'legacy',
    },
  ],
  
  // Default sidebar for standalone pages
  defaultSidebar: [
  ],
};

export default sidebars;
