import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Learn section sidebar
  learnSidebar: [
    {
      type: 'doc',
      id: 'learn/index',
      label: 'Learn',
    },
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'learn/introduction/what-yellow-solves',
        'learn/introduction/architecture-at-a-glance',
        'learn/introduction/supported-chains',
      ],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'learn/core-concepts/state-channels-vs-l1-l2',
        'learn/core-concepts/challenge-response',
        'learn/core-concepts/yellow-token',
      ],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Protocol Flows',
      items: [
        {type: 'autogenerated', dirName: 'learn/protocol-flows'},
      ],
      collapsible: false,
      collapsed: false,
    },
  ],
  
  // Build section sidebar
  buildSidebar: [
    {
      type: 'autogenerated',
      dirName: 'build',
    },
  ],
  
  // Tutorials section sidebar
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],

  // API Reference section sidebar
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
  
  // Protocol section sidebar — only protocol-reference and terminology remain
  // (introduction, architecture, decentralized-layer moved to Clearnet)
  protocolSidebar: [
    'protocol/protocol-reference',
    'protocol/terminology',
  ],
  
  // Default sidebar for standalone pages
  defaultSidebar: [
  ],
};

export default sidebars;
