import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Learn section sidebar
  tutorialSidebar: [
    'learn/index',
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/introduction',
        },
      ],
    },
    {
      type: 'category',
      label: 'Beginner',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/beginner',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn/advanced',
        },
      ],
    },
  ],

  // Build section sidebar
  buildSidebar: [
    {
      type: 'autogenerated',
      dirName: 'build',
    },
  ],

  // Manuals section sidebar
  manualsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'manuals',
    },
  ],

  // Tutorials section sidebar
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],

  // API Reference sidebar
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],

  // Legacy sidebar
  legacySidebar: [
    {
      type: 'autogenerated',
      dirName: 'legacy',
    },
  ],
};

export default sidebars;
