import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  clearnetSidebar: [
    'learn/introduction',
    'learn/architecture',
    {
      type: 'category',
      label: 'Decentralized Layer',
      items: [
        {type: 'autogenerated', dirName: 'learn/decentralized-layer'},
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Contracts',
      items: [
        {type: 'autogenerated', dirName: 'learn/contracts'},
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
